packages:
  - "packages/*"
  - "packages/clients/*"
  - "packages/balances/*"
  - "packages/balances/providers/*"
  - "packages/connectors/*"
  - "packages/connectors/providers/*"
  - "packages/tokens/*"
  - "packages/tokens/providers/*"
  - "apps/*"
