packages:
  - "packages/*"
  - "packages/clients/*"
  - "packages/connectors/*"
  - "packages/connectors/providers/*"
  - "packages/notes/*"
  - "packages/oracle/*"
  - "packages/oracle/providers/*"
  - "packages/tokens/*"
  - "apps/*"
