/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpikeRouteImport } from './routes/spike'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as AuthedChar123PageChar125RouteImport } from './routes/_authed/{-$page}'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLogoTokenIdRouteImport } from './routes/api/logo/token/$id'
import { Route as ApiLogoPlatformKeyRouteImport } from './routes/api/logo/platform/$key'
import { Route as ApiLogoDefiProtocolRouteImport } from './routes/api/logo/defi/$protocol'

const SpikeRoute = SpikeRouteImport.update({
  id: '/spike',
  path: '/spike',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChar123PageChar125Route =
  AuthedChar123PageChar125RouteImport.update({
    id: '/{-$page}',
    path: '/{-$page}',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoTokenIdRoute = ApiLogoTokenIdRouteImport.update({
  id: '/api/logo/token/$id',
  path: '/api/logo/token/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoPlatformKeyRoute = ApiLogoPlatformKeyRouteImport.update({
  id: '/api/logo/platform/$key',
  path: '/api/logo/platform/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoDefiProtocolRoute = ApiLogoDefiProtocolRouteImport.update({
  id: '/api/logo/defi/$protocol',
  path: '/api/logo/defi/$protocol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/spike': typeof SpikeRoute
  '/{-$page}': typeof AuthedChar123PageChar125Route
  '/api/export': typeof ApiExportRoute
  '/api/import': typeof ApiImportRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logo/defi/$protocol': typeof ApiLogoDefiProtocolRoute
  '/api/logo/platform/$key': typeof ApiLogoPlatformKeyRoute
  '/api/logo/token/$id': typeof ApiLogoTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/spike': typeof SpikeRoute
  '/{-$page}': typeof AuthedChar123PageChar125Route
  '/api/export': typeof ApiExportRoute
  '/api/import': typeof ApiImportRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logo/defi/$protocol': typeof ApiLogoDefiProtocolRoute
  '/api/logo/platform/$key': typeof ApiLogoPlatformKeyRoute
  '/api/logo/token/$id': typeof ApiLogoTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/spike': typeof SpikeRoute
  '/_authed/{-$page}': typeof AuthedChar123PageChar125Route
  '/api/export': typeof ApiExportRoute
  '/api/import': typeof ApiImportRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logo/defi/$protocol': typeof ApiLogoDefiProtocolRoute
  '/api/logo/platform/$key': typeof ApiLogoPlatformKeyRoute
  '/api/logo/token/$id': typeof ApiLogoTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/spike'
    | '/{-$page}'
    | '/api/export'
    | '/api/import'
    | '/api/sync'
    | '/api/auth/$'
    | '/api/logo/defi/$protocol'
    | '/api/logo/platform/$key'
    | '/api/logo/token/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/spike'
    | '/{-$page}'
    | '/api/export'
    | '/api/import'
    | '/api/sync'
    | '/api/auth/$'
    | '/api/logo/defi/$protocol'
    | '/api/logo/platform/$key'
    | '/api/logo/token/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/spike'
    | '/_authed/{-$page}'
    | '/api/export'
    | '/api/import'
    | '/api/sync'
    | '/api/auth/$'
    | '/api/logo/defi/$protocol'
    | '/api/logo/platform/$key'
    | '/api/logo/token/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SpikeRoute: typeof SpikeRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiImportRoute: typeof ApiImportRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLogoDefiProtocolRoute: typeof ApiLogoDefiProtocolRoute
  ApiLogoPlatformKeyRoute: typeof ApiLogoPlatformKeyRoute
  ApiLogoTokenIdRoute: typeof ApiLogoTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spike': {
      id: '/spike'
      path: '/spike'
      fullPath: '/spike'
      preLoaderRoute: typeof SpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/{-$page}': {
      id: '/_authed/{-$page}'
      path: '/{-$page}'
      fullPath: '/{-$page}'
      preLoaderRoute: typeof AuthedChar123PageChar125RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo/token/$id': {
      id: '/api/logo/token/$id'
      path: '/api/logo/token/$id'
      fullPath: '/api/logo/token/$id'
      preLoaderRoute: typeof ApiLogoTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo/platform/$key': {
      id: '/api/logo/platform/$key'
      path: '/api/logo/platform/$key'
      fullPath: '/api/logo/platform/$key'
      preLoaderRoute: typeof ApiLogoPlatformKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo/defi/$protocol': {
      id: '/api/logo/defi/$protocol'
      path: '/api/logo/defi/$protocol'
      fullPath: '/api/logo/defi/$protocol'
      preLoaderRoute: typeof ApiLogoDefiProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedChar123PageChar125Route: typeof AuthedChar123PageChar125Route
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChar123PageChar125Route: AuthedChar123PageChar125Route,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SpikeRoute: SpikeRoute,
  ApiExportRoute: ApiExportRoute,
  ApiImportRoute: ApiImportRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLogoDefiProtocolRoute: ApiLogoDefiProtocolRoute,
  ApiLogoPlatformKeyRoute: ApiLogoPlatformKeyRoute,
  ApiLogoTokenIdRoute: ApiLogoTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
